global using System.Collections.Concurrent;
global using System.Collections.Frozen;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.IO.Compression;
global using System.Runtime.CompilerServices;
global using System.Security;
global using System.Xml;
global using static Month;
global using static AustralianHolidays.State;